var stats = {
    energy: {
        current: 10,
        increase: 0.02,
        speed: 500,
        speedModifier: 1,
        max: 10,
        originalMax: 10,
        coffee: {
            total: 0,
            current: 0,
            timer: 60,
            cooldown: 300,
            boost: 5,
            isActive: false,
            isCooldown: false,
        }
    },
    strength: 0,
    strengthBoost: .001,
    endurance: 0,
    enduranceBoost: .001,
    agility: 0,
    agilityBoost: .001,
    intelligence: 0,
    intelligenceBoost: .001,
    allStatBoost: .000125,
    money: 0,
    payday: {
        total: 0,
        current: 0,
        cooldown: 300,
        boost: 100,
        isCooldown: false,
    },
    prestigePoints: 0,
    bodyweightPoints: 0,
    liftingPoints: 0,
    yogaPoints: 0,
    cardioPoints: 0,
    totalPrestige: 0,
    totalBwPrestige: 0,
    totalLiftingPrestige: 0,
    totalYogaPrestige: 0,
    totalCardioPrestige: 0,
    saveTime: 0,
    gameVersion: .53,
};
var bodyweight = {
    pushups: {
        id: 0,
        isStopped: 0,
        total: 0,
        current: 0,
        increase: 10,
        speed: 1000,
        speedModifier: 1,
        max: 50,
        energy: 1,
        strength: .05,
        endurance: .025,
        agility: .01,
        tier: 0,
        tiers: [
            {
                name: "Incline Pushups",
                multiplier: 2,
                upgrade: 100,
            },
            {
                name: "Pushups",
                multiplier: 2,
                upgrade: 1000,
            },
            {
                name: "Diamond Pushups",
                multiplier: 2,
                upgrade: 10000,
            },
            {
                name: "Pseudo Planche Pushups",
                multiplier: 2,
                upgrade: 100000,
            },
            {
                name: "Planche Pushups",
                multiplier: 2,
                upgrade: 100000,
            }
        ],
    },
    rows: {
        id: 1,
        isStopped: 0,
        total: 0,
        current: 0,
        increase: 10,
        speed: 1000,
        speedModifier: 1,
        max: 50,
        energy: 1,
        strength: .025,
        endurance: .05,
        agility: .01,
        tier: 0,
        tiers: [
            {
                name: "Incline Rows",
                multiplier: 2,
                upgrade: 100,
            },
            {
                name: "Horizontal Rows",
                multiplier: 2,
                upgrade: 1000,
            },
            {
                name: "Tuck Front Lever Rows",
                multiplier: 2,
                upgrade: 10000,
            },
            {
                name: "Advanced Tuck Front Lever Rows",
                multiplier: 2,
                upgrade: 100000,
            },
            {
                name: "Front Lever Rows",
                multiplier: 2,
                upgrade: 100000,
            }
        ],
    },
    dips: {
        id: 2,
        isStopped: 0,
        total: 0,
        current: 0,
        increase: 10,
        speed: 1000,
        speedModifier: 1,
        max: 50,
        energy: 2,
        strength: .05,
        endurance: .1,
        agility: .02,
        tier: 0,
        tiers: [
            {
                name: "Support Holds",
                multiplier: 2,
                upgrade: 100,
            },
            {
                name: "Dip Negatives",
                multiplier: 2,
                upgrade: 1000,
            },
            {
                name: "Dips",
                multiplier: 2,
                upgrade: 10000,
            },
            {
                name: "Ring Dips",
                multiplier: 2,
                upgrade: 100000,
            },
            {
                name: "Rings Turned-Out Dips",
                multiplier: 2,
                upgrade: 100000,
            }
        ],
    },
    pullups: {
        id: 3,
        isStopped: 0,
        total: 0,
        current: 0,
        increase: 10,
        speed: 1000,
        speedModifier: 1,
        max: 50,
        energy: 2,
        strength: .1,
        endurance: .05,
        agility: .02,
        tier: 0,
        tiers: [
            {
                name: "Arch Hangs",
                multiplier: 2,
                upgrade: 100,
            },
            {
                name: "Pullup Negatives",
                multiplier: 2,
                upgrade: 1000,
            },
            {
                name: "Pullups",
                multiplier: 2,
                upgrade: 10000,
            },
            {
                name: "Assisted One-Arm Pullups",
                multiplier: 2,
                upgrade: 100000,
            },
            {
                name: "One-Arm Pullups",
                multiplier: 2,
                upgrade: 100000,
            }
        ],
    },
    squats: {
        id: 4,
        isStopped: 0,
        total: 0,
        current: 0,
        increase: 10,
        speed: 1000,
        speedModifier: 1,
        max: 50,
        energy: 4,
        strength: .15,
        endurance: .05,
        agility: .15,
        tier: 0,
        tiers: [
            {
                name: "Assisted Squat",
                multiplier: 2,
                upgrade: 100,
            },
            {
                name: "Squat",
                multiplier: 2,
                upgrade: 1000,
            },
            {
                name: "Split Squat",
                multiplier: 2,
                upgrade: 10000,
            },
            {
                name: "Bulgarian Split Squat",
                multiplier: 2,
                upgrade: 100000,
            },
            {
                name: "Pistol Squat",
                multiplier: 2,
                upgrade: 100000,
            }
        ],

    },
    rdl: {
        id: 5,
        isStopped: 0,
        total: 0,
        current: 0,
        increase: 10,
        speed: 1000,
        speedModifier: 1,
        max: 50,
        energy: 4,
        strength: .15,
        endurance: .05,
        agility: .15,
        tier: 0,
        tiers: [
            {
                name: "Romanian Deadlifts (No Weight)",
                multiplier: 2,
                upgrade: 100,
            },
            {
                name: "Single-Legged Deadlifts",
                multiplier: 2,
                upgrade: 1000,
            },
            {
                name: "Banded Nordic Curl Negatives",
                multiplier: 2,
                upgrade: 10000,
            },
            {
                name: "Banded Nordic Curls",
                multiplier: 2,
                upgrade: 100000,
            },
            {
                name: "Nordic Curls",
                multiplier: 2,
                upgrade: 100000,
            }
        ],
    },
    upgrades: [
        {
            id: 0,
            isActive: false,
            isPurchased: false,
            name: "Homemade Pushup Handles",
            desc: "<strong>Cost: $2.5</strong> - Pushup handles should double my pushup speed. That's how physics work.",
            cost: 2.5,
        },
        {
            id: 1,
            isActive: false,
            isPurchased: false,
            name: "Homemade Gymnastic Rings",
            desc: "<strong>Cost: $7.5</strong> - These cheaply made gymnastic rings should let me do rows. Once I do some research, I should be able to do dips too.",
            cost: 7.5,
        },
        {
            id: 2,
            isActive: false,
            isPurchased: false,
            name: "Pay a Friend to Teach You",
            desc: "<strong>Cost: $25</strong> - My friend wants to show me the correct way to do pushups and rows. Halves the energy expenditure of pushups and rows.",
            cost: 25,
        },
        {
            id: 3,
            isActive: false,
            isPurchased: false,
            name: "Buy Wooden Gymnastic Rings",
            desc: "<strong>Cost: $50</strong> - These nice, wooden made gymnastic rings should let me do rows at double speed.",
            cost: 50,
        },
        {
            id: 4,
            isActive: false,
            isPurchased: false,
            name: "Buy Pullup Bar",
            desc: "<strong>Cost: $100</strong> - I'm flying! Unlocks Pullups.",
            cost: 100,
        },
        {
            id: 5,
            isActive: false,
            isPurchased: false,
            name: "Pay for Pullup Training",
            desc: "<strong>Cost: $250</strong> - My friend keeps wanting more money. Doubles pullup speed.",
            cost: 250,
        },
        {
            id: 6,
            isActive: false,
            isPurchased: false,
            name: "Pay for Dip Training",
            desc: "<strong>Cost: $250</strong> - I'm seriously getting mad at this guy. Doubles dip speed.",
            cost: 250,
        },
        {
            id: 7,
            isActive: false,
            isPurchased: false,
            name: "Create a Home Gym",
            desc: "<strong>Cost: $500</strong> - With proper equipment, anything is possible. Halves the energy expenditure of pullups.",
            cost: 500,
        },
        {
            id: 8,
            isActive: false,
            isPurchased: false,
            name: "Mount Rings and Expand Home Gym",
            desc: "<strong>Cost: $500</strong> - Mounted rings should give me a more stable platform for dips. Halves the energy expenditure of dips.",
            cost: 500,
        },
        {
            id: 9,
            isActive: false,
            isPurchased: false,
            name: "Pay for Squat Training",
            desc: "<strong>Cost: $1000</strong> - How does my friend know I have all this money. Is he a follower of mine? Doubles Squat Speed.",
            cost: 1000,
        },
        {
            id: 10,
            isActive: false,
            isPurchased: false,
            name: "Pay Romanian Deadlift Training",
            desc: "<strong>Cost: $1000</strong> - Maybe he's trying to launch a competing channel? Doubles Romanian Deadlift Speed.",
            cost: 1000,
        },
        {
            id: 11,
            isActive: false,
            isPurchased: false,
            name: "Pay for Leg Hypertrophy Guide",
            desc: "<strong>Cost: $2500</strong> - Seems reasonable. Halves the energy expenditure of bodyweight leg exercises.",
            cost: 2500,
        },
        {
            id: 12,
            isActive: false,
            isPurchased: false,
            name: "Better Form for Pushups and Rows",
            desc: "<strong>Cost: $5000</strong> - Double energy expenditure of pushups and rows, but double stat gains as well.",
            cost: 5000,
        },
        {
            id: 13,
            isActive: false,
            isPurchased: false,
            name: "Better Form for Dips and Pullups",
            desc: "<strong>Cost: $10000</strong> - Double energy expenditure of dips and pullups, but double stat gains as well.",
            cost: 10000,
        },
        {
            id: 14,
            isActive: false,
            isPurchased: false,
            name: "Better Form for Bodyweight Legs Exercises",
            desc: "<strong>Cost: $25000</strong> - Double energy expenditure of bodyweight leg exercises, but double stat gains as well.",
            cost: 25000,
        }
    ],
    gang: {
        on: 0,
        name: "Your Gang",
        strength: 0,
        strengthAmount: .2,
        members: 0,
        memberAmount: .02,
        playerFightPowerTemp: 0,
        rivalFightPowerTemp: 0,
        rivalId: -1,
        rivals: [
            {
                name: "Girl Scouts",
                desc: "They need to earn their 'gainz' badge",
                strength: 20,
                strengthAmount: .001,
                members: 5,
                memberAmount: .0001,
                isDefeated: false,
                isAbsorbed: false,
            },
            {
                name: "Lumbering Llamas",
                desc: "Slow and steady, time under tension",
                strength: 40,
                strengthAmount: .002,
                members: 10,
                memberAmount: .0002,
                isDefeated: false,
                isAbsorbed: false,
            },
            {
                name: "Bored Gamers",
                desc: "They've played it all, and now they're playing a real life incremental game",
                strength: 80,
                strengthAmount: .003,
                members: 20,
                memberAmount: .0003,
                isDefeated: false,
                isAbsorbed: false,
            },
            {
                name: "Bob Squad",
                desc: "Only Bobs need apply",
                strength: 160,
                strengthAmount: .004,
                members: 40,
                memberAmount: .0004,
                isDefeated: false,
                isAbsorbed: false,
            },
            {
                name: "Screaming Cats",
                desc: "Every rep is loud and obnoxious",
                strength: 320,
                strengthAmount: .005,
                members: 80,
                memberAmount: .0005,
                isDefeated: false,
                isAbsorbed: false,
            },
            {
                name: "Bootcamp Brides",
                desc: "They got in shape for their wedding and they're ready to prove it",
                strength: 640,
                strengthAmount: .006,
                members: 160,
                memberAmount: .0006,
                isDefeated: false,
                isAbsorbed: false,
            },
            {
                name: "Obvious Onions",
                desc: "Prepare to cry",
                strength: 1280,
                strengthAmount: .007,
                members: 320,
                memberAmount: .0007,
                isDefeated: false,
                isAbsorbed: false,
            },
            {
                name: "Skull Busters",
                desc: "You know they're serious when the name is serious",
                strength: 1920,
                strengthAmount: .008,
                members: 480,
                memberAmount: .0008,
                isDefeated: false,
                isAbsorbed: false,
            },
            {
                name: "Shriveled Prunes",
                desc: "These grannies are deceptively agile",
                strength: 2880,
                strengthAmount: .009,
                members: 720,
                memberAmount: .0009,
                isDefeated: false,
                isAbsorbed: false,
            },
            {
                name: "Dream Eaters",
                desc: "They're so good that they make you question your life choices",
                strength: 4320,
                strengthAmount: .01,
                members: 1080,
                memberAmount: .001,
                isDefeated: false,
                isAbsorbed: false,
            },
        ],
    },
};

var lifting = {
    bench: {
        id: 6,
        name: "Bench Press",
        isStopped: 0,
        total: 0,
        current: 0,
        increase: 10,
        speed: 1000,
        speedModifier: 1,
        max: 100,
        energy: 4,
        strength: .2,
        endurance: .1,
        agility: .04,
        weight: 45,
        weightIncrease: 5,
        multi: 1.02,
        maxWeight: 750,
        repsToNext: 0,
        repsToNextBase: 2,
    },
    rows: {
        id: 7,
        name: "Barbell Row",
        isStopped: 0,
        total: 0,
        current: 0,
        increase: 10,
        speed: 1000,
        speedModifier: 1,
        max: 100,
        energy: 4,
        strength: .1,
        endurance: .2,
        agility: .04,
        weight: 45,
        weightIncrease: 5,
        multi: 1.02,
        maxWeight: 750,
        repsToNext: 0,
        repsToNextBase: 2,
    },
    ohp: {
        id: 8,
        name: "Overhead Press",
        isStopped: 0,
        total: 0,
        current: 0,
        increase: 10,
        speed: 1000,
        speedModifier: 1,
        max: 50,
        energy: 1,
        strength: .01,
        endurance: .025,
        agility: .05,
        weight: 45,
        weightIncrease: 2.5,
        multi: 1.02,
        maxWeight: 400,
        repsToNext: 0,
        repsToNextBase: 5,
    },
    squats: {
        id: 9,
        name: "Squats",
        isStopped: 0,
        total: 0,
        current: 0,
        increase: 10,
        speed: 1000,
        speedModifier: 1,
        max: 100,
        energy: 8,
        strength: .3,
        endurance: .2,
        agility: .2,
        weight: 45,
        weightIncrease: 10,
        multi: 1.02,
        maxWeight: 1500,
        repsToNext: 0,
        repsToNextBase: 2,
    },
    dls: {
        id: 10,
        name: "Deadlift",
        isStopped: 0,
        total: 0,
        current: 0,
        increase: 10,
        speed: 1000,
        speedModifier: 1,
        max: 100,
        energy: 8,
        strength: .4,
        endurance: .1,
        agility: .2,
        weight: 45,
        weightIncrease: 10,
        multi: 1.02,
        maxWeight: 1500,
        repsToNext: 0,
        repsToNextBase: 2,
    },
    curls: {
        id: 11,
        name: "Barbell Curls",
        isStopped: 0,
        total: 0,
        current: 0,
        increase: 10,
        speed: 1000,
        speedModifier: 1,
        max: 50,
        energy: 1,
        strength: .025,
        endurance: .03,
        agility: .03,
        weight: 45,
        weightIncrease: 1.25,
        multi: 1.02,
        maxWeight: 225,
        repsToNext: 0,
        repsToNextBase: 10,
    },
    comps: {
        competitions: {
            id: 0,
            current: 0,
            mod: .025,
        },
        conferences: {
            id: 1,
            current: 0,
            cost: 10,
            multi: 2,
            mod: .025,
            hidden: false,
        },
        regionalConferences: {
            id: 2,
            current: 0,
            cost: 10000,
            multi: 2,
            mod: .025,
            hidden: false,
        },
        stateConferences: {
            id: 3,
            current: 0,
            cost: 10000000,
            multi: 2,
            mod: .025,
            hidden: false,
        },
        nationalConferences: {
            id: 4,
            current: 0,
            cost: 10000000000,
            multi: 2,
            mod: .025,
            hidden: false,
        },
        worldConferences: {
            id: 5,
            current: 0,
            cost: 10000000000000,
            multi: 2,
            mod: .025,
            hidden: false,
        },
    }
};

var upgrades = [
    {
        id: 0,
        isActive: false,
        isPurchased: false,
        name: "Buy Coffee",
        desc: "<strong>Cost: $1</strong> - Increase energy with coffee",
        cost: 1
    },
    {
        id: 1,
        isActive: false,
        isPurchased: false,
        name: "Buy Stronger Coffee",
        desc: "<strong>Cost: $5</strong> - Increase energy with coffee",
        cost: 5
    },
    {
        id: 2,
        isActive: false,
        isPurchased: false,
        name: "Buy Creatine",
        desc: "<strong>Cost: $10</strong> - Creatine will double your energy recovery.",
        cost: 10
    },
    {
        id: 3,
        isActive: false,
        isPurchased: false,
        name: "Protein Shakes",
        desc: "<strong>Cost: $50</strong> - Protein shakes let you build strength faster. Why get your protein from chicken when you can drink it. Makes strength more effective.",
        cost: 50
    },
    {
        id: 4,
        isActive: false,
        isPurchased: false,
        name: "Buy Endurance Supplements",
        desc: "<strong>Cost: $100</strong> - Supplements should give my endurance more of an impact.",
        cost: 100
    },
    {
        id: 5,
        isActive: false,
        isPurchased: false,
        name: "Buy Agility Supplements",
        desc: "<strong>Cost: $250</strong> - Supplements should give my agility more of an impact.",
        cost: 250
    },
    {
        id: 6,
        isActive: false,
        isPurchased: false,
        name: "Buy Intelligence Supplements",
        desc: "<strong>Cost: $500</strong> - Supplements should give my intelligence more of an impact.",
        cost: 500
    },
    {
        id: 7,
        isActive: false,
        isPurchased: false,
        name: "Purchase Bulk Supplements to Sell",
        desc: "<strong>Cost: $1000</strong> - Increases follower growth based on all stats.",
        cost: 1000
    },
    {
        id: 8,
        isActive: false,
        isPurchased: false,
        name: "Buy L-Citrulline in Bulk",
        desc: "<strong>Cost: $2500</strong> - A bit more expensive, but doubles energy recovery again.",
        cost: 2500
    },
    {
        id: 9,
        isActive: false,
        isPurchased: false,
        name: "Experimental Supplements for Strength",
        desc: "<strong>Cost: $5000</strong> - Very expensive, but doubles the effectiveness of strength.",
        cost: 5000
    },
    {
        id: 10,
        isActive: false,
        isPurchased: false,
        name: "Experimental Supplements for Agility",
        desc: "<strong>Cost: $10000</strong> - Very expensive, but doubles the effectiveness of agility.",
        cost: 10000
    },
    {
        id: 11,
        isActive: false,
        isPurchased: false,
        name: "Experimental Supplements for Endurance",
        desc: "<strong>Cost: $25000</strong> - Very expensive, but doubles the effectiveness of endurance.",
        cost: 25000
    },
    {
        id: 12,
        isActive: false,
        isPurchased: false,
        name: "Experimental Supplements for Intelligence",
        desc: "<strong>Cost: $50000</strong> - Very expensive, but doubles the effectiveness of intelligence.",
        cost: 50000
    }
];

var job = {
    makeVideo: {
        total: 0,
        current: 0,
        increase: 10,
        speed: 1000,
        speedModifier: 2,
        max: 100,
    },
    recruitInfluencers: {
        total: 0,
        current: 0,
        increase: 5,
        speed: 1000,
        speedModifier: 2,
        max: 100,
    },
    followers: 0.00,
    views: 0.00,
    influencers: 0.00,
    influencerGrowth: .05,
    influencerMulti: .00005,
    followerGrowth: .1,
    viewGrowth: .001,
    moneyGrowth: .00001,
    moneyDrain: 0.00,
    pushupFollowerMod: 0.00,
    rowFollowerMod: 0.00,
    dipFollowerMod: 0.00,
    pullupFollowerMod: 0.00,
    bwSquatFollowerMod: 0.00,
    bwRdlFollowerMod: 0.00,
    postFollowerMod: 0.00,
    upgrades: [
        {
            id: 0,
            isActive: false,
            isPurchased: false,
            name: "Go Viral Accidentally",
            desc: "<strong>Cost: 1 follower</strong> - Not sure what happened. Adds 5000 views",
            cost: 1,
        },
        {
            id: 29,
            isActive: false,
            isPurchased: false,
            name: "Collect Revenue",
            desc: "<strong>Cost: 1 followers</strong> - Allows you to periodically collect your earnings!",
            cost: 1,
        },
        {
            id: 1,
            isActive: false,
            isPurchased: false,
            name: "Make Misleading Claims",
            desc: "<strong>Cost: 1 followers</strong> - No one will ever realize I'm talking nonsense. Double your work speed.",
            cost: 1,
        },
        {
            id: 2,
            isActive: false,
            isPurchased: false,
            name: "Livestream Pushups",
            desc: "<strong>Cost: 2.5 follower</strong> - Annoy some followers by livestreaming pushups all day. Adds a portion of your total pushups to your follower growth.",
            cost: 2.5,
        },
        {
            id: 3,
            isActive: false,
            isPurchased: false,
            name: "Livestream Rows",
            desc: "<strong>Cost: 2.5 follower</strong> - Annoy some followers by livestreaming rows all day. Adds a portion of your total rows to your follower growth.",
            cost: 2.5,
        },
        {
            id: 4,
            isActive: false,
            isPurchased: false,
            name: "Speculate About Fitness",
            desc: "<strong>Cost: 5 followers</strong> - Unlocks research.",
            cost: 5,
        },
        {
            id: 5,
            isActive: false,
            isPurchased: false,
            name: "Clickbait Titles",
            desc: "<strong>Cost: 7.5 followers</strong> - Change all of your video titles to scare people into clicking. Views go up faster per follower.",
            cost: 7.5,
        },
        {
            id: 6,
            isActive: false,
            isPurchased: false,
            name: "Put Ads on Videos",
            desc: "<strong>Cost: 10 followers</strong> - Everyone loves ads! Double your money per view.",
            cost: 10,
        },
        {
            id: 7,
            isActive: false,
            isPurchased: false,
            name: "Get Sponsors",
            desc: "<strong>Cost: 15 followers</strong> - I'm becoming an influencer. Double the effectiveness of stats on follower growth.",
            cost: 15,
        },
        {
            id: 8,
            isActive: false,
            isPurchased: false,
            name: "Guest Stars",
            desc: "<strong>Cost: 50 followers</strong> - Bring some important people into the channel to discuss with me. Intelligence gain is doubled from research.",
            cost: 50,
        },
        {
            id: 9,
            isActive: false,
            isPurchased: false,
            name: "Plug Products",
            desc: "<strong>Cost: 100 followers</strong> - Carefully place products in my videos. Double the views per follower.",
            cost: 100,
        },
        {
            id: 10,
            isActive: false,
            isPurchased: false,
            name: "Compete in Pullup Contest",
            desc: "<strong>Cost: 250 followers</strong> - Everyone loves a contest. Adds pullups to follower growth.",
            cost: 250,
        },
        {
            id: 11,
            isActive: false,
            isPurchased: false,
            name: "Compete in Dip Contest",
            desc: "<strong>Cost: 250 followers</strong> - Well, maybe not everyone loves a contest. I love contests. Adds dips to follower growth.",
            cost: 250,
        },
        {
            id: 12,
            isActive: false,
            isPurchased: false,
            name: "Film Squats",
            desc: "<strong>Cost: 500 followers</strong> - Everyone wants to see some squats. Adds squats to follower growth.",
            cost: 500,
        },
        {
            id: 13,
            isActive: false,
            isPurchased: false,
            name: "Film Romanian Deadlifts",
            desc: "<strong>Cost: 500 followers</strong> - No one can ever do romanian deadlifts correctly. I'll show them. Adds romanian deadlifts to follower growth.",
            cost: 500,
        },
        {
            id: 14,
            isActive: false,
            isPurchased: false,
            name: "Bring Research into Videos",
            desc: "<strong>Cost: 1000 followers</strong> - Maybe I'll make things more scientific. Adds a portion of your total posts to follower growth.",
            cost: 1000,
        },
        {
            id: 15,
            isActive: false,
            isPurchased: false,
            name: "Refine Marketing Techniques",
            desc: "<strong>Cost: 2500 followers</strong> - I must learn the secrets of the dark side. Double views per follower.",
            cost: 2500,
        },
        {
            id: 16,
            isActive: false,
            isPurchased: false,
            name: "Coordinate Better with Influencers",
            desc: "<strong>Cost: 5000 followers</strong> - I need to get coordinated to bring more followers into my channel. Double influencer growth.",
            cost: 5000,
        },
        {
            id: 17,
            isActive: false,
            isPurchased: false,
            name: "Advertise with Influencers",
            desc: "<strong>Cost: 10000 followers</strong> - Placing ads on my influencer's pages will add to follower growth per influencer.",
            cost: 10000,
        },
        {
            id: 18,
            isActive: false,
            isPurchased: false,
            name: "Show Off Body",
            desc: "<strong>Cost: 25000 followers</strong> - I'm getting buff. Doubles the influence of stats on follower growth.",
            cost: 25000,
        },
        {
            id: 19,
            isActive: false,
            isPurchased: false,
            name: "Planned Viral Video",
            desc: "<strong>Cost: 250 followers</strong> - Work with influencers to go 'viral'. Doubles the recruitment of influencers.",
            cost: 250,
        },
        {
            id: 20,
            isActive: false,
            isPurchased: false,
            name: "Send Marketing Emails",
            desc: "<strong>Cost: 75 followers</strong> - Market to your audience. Doubles views per follower.",
            cost: 75,
        },
        {
            id: 21,
            isActive: false,
            isPurchased: false,
            name: "Put Link to Workout Plan in Bio",
            desc: "<strong>Cost: 25 followers</strong> - Get that sweet money. Doubles views per follower.",
            cost: 25,
        },
        {
            id: 22,
            isActive: false,
            isPurchased: false,
            name: "Scream Very Loudly in All Workout Videos",
            desc: "<strong>Cost: 25 followers</strong> - Yelling always makes people love you. Doubles follower growth.",
            cost: 25,
        },
        {
            id: 23,
            isActive: false,
            isPurchased: false,
            name: "Try to Look Smarter",
            desc: "<strong>Cost: 7500 followers</strong> - First impressions count. Doubles intelligence from research.",
            cost: 7500,
        },
        {
            id: 24,
            isActive: false,
            isPurchased: false,
            name: "Ads Within Ads",
            desc: "<strong>Cost: 1000 followers</strong> - Adception. Doubles views per follower.",
            cost: 1000,
        },
        {
            id: 25,
            isActive: false,
            isPurchased: false,
            name: "Put Followers to Work",
            desc: "<strong>Cost: 15000 followers</strong> - Ask questions online so they can do your research. Doubles research speed.",
            cost: 15000,
        },
        {
            id: 26,
            isActive: false,
            isPurchased: false,
            name: "Sell Supplements on Channel",
            desc: "<strong>Cost: 25 followers</strong> - This won't annoy anyone! Doubles money growth.",
            cost: 25,
        },
        {
            id: 27,
            isActive: false,
            isPurchased: false,
            name: "Put Influencers to Work",
            desc: "<strong>Cost: 50000 followers</strong> - Get influencers researching too. Doubles research speed.",
            cost: 50000,
        },
        {
            id: 28,
            isActive: false,
            isPurchased: false,
            name: "Ads Within Ads Within Ads",
            desc: "<strong>Cost: 5000 followers</strong> - Double Adception. Doubles money growth.",
            cost: 5000,
        },
    ],
};

var research = {
    browseReddit: {
        total: 0,
        current: 0,
        increase: 5,
        speed: 1000,
        speedModifier: 3,
        max: 100,
        intelligence: .05,
    },
    codeBots: {
        total: 0,
        current: 0,
        increase: 2.5,
        speed: 1000,
        speedModifier: 3,
        max: 100,
        intelligence: .1,
    },
    posts: 0.00,
    points: 0.00,
    bots: 0.00,
    pointSpeed: 1000,
    postGrowth: 1,
    postStrengthMod: 0,
    pointGrowth: .0001,
    botGrowth: 0.25,
    botSpeed: 1000,
    botMulti: .00005,
    upgrades: [
        {
            id: 0,
            isActive: false,
            isPurchased: false,
            name: "Effective Marketing",
            desc: "<strong>Cost: 1 research</strong> - Market your channel in your posts to double follower growth.",
            cost: 1,
        },
        {
            id: 1,
            isActive: false,
            isPurchased: false,
            name: "Sleeping Better",
            desc: "<strong>Cost: 2.5 research</strong> - It's time to get serious about sleep hygiene. Double your energy recovery.",
            cost: 2.5,
        },
        {
            id: 2,
            isActive: false,
            isPurchased: false,
            name: "Sort Comments by Best",
            desc: "<strong>Cost: 5 research</strong> - The best sorting is best. Double your research speed.",
            cost: 5,
        },
        {
            id: 3,
            isActive: false,
            isPurchased: false,
            name: "Study Other YouTube Channels",
            desc: "<strong>Cost: 5 research</strong> - How are they monetizing their channel? Double your money growth.",
            cost: 5,
        },
        {
            id: 4,
            isActive: false,
            isPurchased: false,
            name: "Dips",
            desc: "<strong>Cost: 7.5 research</strong> - When I dip you dip we dip. Unlocks dips.",
            cost: 7.5,
        },
        {
            id: 5,
            isActive: false,
            isPurchased: false,
            name: "Hypertrophy",
            desc: "<strong>Cost: 10 research</strong> - How to build muscle. Doubles the effectiveness of strength.",
            cost: 10,
        },
        {
            id: 6,
            isActive: false,
            isPurchased: false,
            name: "Hide Downvoted Posts",
            desc: "<strong>Cost: 10 research</strong> - No bad comments allowed. Doubles research speed.",
            cost: 10,
        },
        {
            id: 7,
            isActive: false,
            isPurchased: false,
            name: "High Intensity Interval Training",
            desc: "<strong>Cost: 25 research</strong> - Get that heart rate up! Doubles the effectiveness of agility.",
            cost: 25,
        },
        {
            id: 8,
            isActive: false,
            isPurchased: false,
            name: "High Reps",
            desc: "<strong>Cost: 50 research</strong> - How to build endurance. Doubles the effectiveness of endurance.",
            cost: 50,
        },
        {
            id: 9,
            isActive: false,
            isPurchased: false,
            name: "Advanced Research Techniques",
            desc: "<strong>Cost: 100 research</strong> - I am one with the universe. Doubles the effectivess of intelligence.",
            cost: 100,
        },
        {
            id: 10,
            isActive: false,
            isPurchased: false,
            name: "Research Recruiting Influencers",
            desc: "<strong>Cost: 50 research</strong> - Recruit influencers to increase follower growth.",
            cost: 50,
        },
        {
            id: 11,
            isActive: false,
            isPurchased: false,
            name: "Leg Day",
            desc: "<strong>Cost: 250 research</strong> - Stop being a bro. Unlocks squats and romanian deadlifts.",
            cost: 250,
        },
        {
            id: 12,
            isActive: false,
            isPurchased: false,
            name: "Examine Your Beliefs",
            desc: "<strong>Cost: 1000 research</strong> - Double the intelligence growth of research.",
            cost: 1000,
        },
        {
            id: 13,
            isActive: false,
            isPurchased: false,
            name: "Research Bots",
            desc: "<strong>Cost: 250 research</strong> - With bots, I can read posts faster. Unlocks Code Bots.",
            cost: 250,
        },
        {
            id: 14,
            isActive: false,
            isPurchased: false,
            name: "More Effective Bots",
            desc: "<strong>Cost: 2500 research</strong> - Refine the code. Doubles the effect of bots on post growth.",
            cost: 2500,
        },
        {
            id: 15,
            isActive: false,
            isPurchased: false,
            name: "Efficient Coding",
            desc: "<strong>Cost: 5000 research</strong> - Bot growth is doubled.",
            cost: 5000,
        },
        {
            id: 16,
            isActive: false,
            isPurchased: false,
            name: "Learn Speed Reading",
            desc: "<strong>Cost: 10000 research</strong> - You might miss some important facts, but it's just fitness. Doubles post read speed.",
            cost: 10000,
        },
        {
            id: 17,
            isActive: false,
            isPurchased: false,
            name: "Opening a New Gym",
            desc: "<strong>Cost: 25000 research</strong> - Unlock Open Gym (prestige).",
            cost: 25000,
        },
        {
            id: 18,
            isActive: false,
            isPurchased: false,
            name: "Flex Online",
            desc: "<strong>Cost: 25 research</strong> - Learning to flex your smarts online will add your strength modifier to post growth.",
            cost: 25,
        },
        {
            id: 19,
            isActive: false,
            isPurchased: false,
            name: "Posing",
            desc: "<strong>Cost: 2.5 research</strong> - Pose for the camera! Doubles the stat modifier for follower growth.",
            cost: 2.5,
        },
        {
            id: 20,
            isActive: false,
            isPurchased: false,
            name: "Take a Free Marketing Course",
            desc: "<strong>Cost: 500 research</strong> - Thanks internet! Doubles follower growth.",
            cost: 500,
        },
        {
            id: 21,
            isActive: false,
            isPurchased: false,
            name: "Study Influencers",
            desc: "<strong>Cost: 2500 research</strong> - How do these people do it. There must be some secret. Doubles the influencer multiplier on follower growth.",
            cost: 2500,
        },
        {
            id: 22,
            isActive: false,
            isPurchased: false,
            name: "Research Bulking",
            desc: "<strong>Cost: 250 research</strong> - Eat big to get big. Doubles energy recovery.",
            cost: 250,
        },
    ],
};

var gym = {
    employees: {
        trainers: {
            current: 0.00,
            increase: 1.00,
            cost: 1.00,
            costMultiplier: 2.00,
        },
        coordinators: {
            current: 0,
            increase: 1,
            cost: 1,
            costMultiplier: 2,
        },
        nutritionists: {
            current: 0,
            boost: .02,
            cost: 1,
            costMultiplier: 2,
        },
        sales: {
            current: 0,
            boost: .02,
            cost: 1,
            costMultiplier: 2,
        },
    },
    trainMembers: {
        total: 0,
        current: 0,
        increase: 0,
        speed: 1000,
        speedModifier: 2,
        max: 50,
        trainAmount: .1,
        barIncrease: 1.00,
    },
    createClasses: {
        total: 0,
        current: 0,
        increase: 0,
        speed: 1000,
        speedModifier: 2,
        max: 100,
        classAmount: 1,
        barIncrease: 1.00,
    },
    runCampaigns: {
        total: 0,
        current: 0,
        increase: 0,
        speed: 1000,
        speedModifier: 3,
        max: 100,
        barIncrease: 1.00,
        intelligence: .05,
    },
    designAds: {
        total: 0,
        current: 0,
        increase: 0,
        speed: 1000,
        speedModifier: 2,
        max: 200,
        barIncrease: 1.00,
        intelligence: .1,
    },
    money: {
        flatIncrease: 0.00,
        growth: 0.0002,
        classMultiplier: 0.002
    },
    classes: 0,
    members: {
        current: 0,
        capacity: 50,
        growth: .01,
        focusId: 0,
        tiers: [
            {
                id: 0,
                name: "Subpar",
                current: 0,
                multiplier: .10,
            },
            {
                id: 1,
                name: "Untrained",
                current: 0,
                multiplier: .10,
            },
            {
                id: 2,
                name: "Novice",
                current: 0,
                multiplier: .10,
            },
            {
                id: 3,
                name: "Intermediate",
                current: 0,
                multiplier: .10,
            },
            {
                id: 4,
                name: "Proficient",
                current: 0,
                multiplier: .10,
            },
            {
                id: 5,
                name: "Advanced",
                current: 0,
                multiplier: .10,
            },
            {
                id: 6,
                name: "Exceptional",
                current: 0,
                multiplier: .10,
            },
            {
                id: 7,
                name: "Elite",
                current: 0,
                multiplier: .10,
            },
            {
                id: 8,
                name: "World Class",
                current: 0,
                multiplier: .20,
            },
        ]
    },
    advertising: {
        campaigns: 0,
        campaignGrowth: 1,
        ads: 0,
        adGrowth: .1,
        adMulti: .00002,
        influence: 0,
        influenceGrowth: .00002,
        employees: {
            coordinators: {
                current: 0.00,
                increase: 1.00,
                cost: 1.00,
                costMultiplier: 2.00,
            },
            designers: {
                current: 0,
                increase: 1,
                cost: 1,
                costMultiplier: 2,
            },
            managers: {
                current: 0,
                boost: .02,
                cost: 1,
                costMultiplier: 2,
            },
        }
    },
    upgrades: [
        {
            id: 0,
            isActive: false,
            isPurchased: false,
            name: "Buy Stronger Coffee",
            desc: "<strong>Cost: $5</strong> - Increase energy with coffee",
            cost: 5
        },
        {
            id: 1,
            isActive: false,
            isPurchased: false,
            name: "Buy Creatine",
            desc: "<strong>Cost: $10</strong> - Creatine will double your energy recovery.",
            cost: 10
        },
        {
            id: 2,
            isActive: false,
            isPurchased: false,
            name: "Protein Shakes",
            desc: "<strong>Cost: $50</strong> - Protein shakes let you build strength faster. Why get your protein from chicken when you can drink it. Makes strength more effective.",
            cost: 50
        },
        {
            id: 3,
            isActive: false,
            isPurchased: false,
            name: "Buy Endurance Supplements",
            desc: "<strong>Cost: $100</strong> - Supplements should give my endurance more of an impact.",
            cost: 100
        },
        {
            id: 4,
            isActive: false,
            isPurchased: false,
            name: "Buy Agility Supplements",
            desc: "<strong>Cost: $250</strong> - Supplements should give my agility more of an impact.",
            cost: 250
        },
        {
            id: 5,
            isActive: false,
            isPurchased: false,
            name: "Buy Intelligence Supplements",
            desc: "<strong>Cost: $500</strong> - Supplements should give my intelligence more of an impact.",
            cost: 500
        },
        {
            id: 6,
            isActive: false,
            isPurchased: false,
            name: "Buy L-Citrulline in Bulk",
            desc: "<strong>Cost: $2500</strong> - A bit more expensive, but doubles energy recovery again.",
            cost: 2500
        },
        {
            id: 7,
            isActive: false,
            isPurchased: false,
            name: "Experimental Supplements for Strength",
            desc: "<strong>Cost: $5000</strong> - Very expensive, but doubles the effectiveness of strength.",
            cost: 5000
        },
        {
            id: 8,
            isActive: false,
            isPurchased: false,
            name: "Experimental Supplements for Agility",
            desc: "<strong>Cost: $10000</strong> - Very expensive, but doubles the effectiveness of agility.",
            cost: 10000
        },
        {
            id: 9,
            isActive: false,
            isPurchased: false,
            name: "Experimental Supplements for Endurance",
            desc: "<strong>Cost: $25000</strong> - Very expensive, but doubles the effectiveness of endurance.",
            cost: 25000
        },
        {
            id: 10,
            isActive: false,
            isPurchased: false,
            name: "Experimental Supplements for Intelligence",
            desc: "<strong>Cost: $50000</strong> - Very expensive, but doubles the effectiveness of intelligence.",
            cost: 50000
        },
        {
            id: 11,
            isActive: false,
            isPurchased: false,
            name: "Purchase Bulk Supplements to Sell",
            desc: "<strong>Cost: $1000</strong> - Improves gym and research based on all stats.",
            cost: 1000
        },
        {
            id: 12,
            isActive: false,
            isPurchased: false,
            name: "Many Cups of Coffee",
            desc: "<strong>Cost: $1</strong> - Why stop at one? Doubles the time coffee lasts.",
            cost: 1
        },
    ],
    adUpgrades: [
        {
            id: 0,
            isActive: false,
            isPurchased: false,
            name: "Effective Marketing",
            desc: "<strong>Cost: 1 influence</strong> - Market your gym more effectively to double money gain.",
            cost: 1,
        },
        {
            id: 1,
            isActive: false,
            isPurchased: false,
            name: "Sleeping at the Gym",
            desc: "<strong>Cost: 2.5 influence</strong> - It's time to get serious about sleep. Double your energy recovery.",
            cost: 2.5,
        },
        {
            id: 2,
            isActive: false,
            isPurchased: false,
            name: "Work Smarter, Not Harder",
            desc: "<strong>Cost: 5 influence</strong> - Efficiency is key. Double your influence generation.",
            cost: 5,
        },
        {
            id: 3,
            isActive: false,
            isPurchased: false,
            name: "Study the Opposition",
            desc: "<strong>Cost: 5 influence</strong> - How are they monetizing their gyms? Double your money growth.",
            cost: 5,
        },
        {
            id: 4,
            isActive: false,
            isPurchased: false,
            name: "Setup Hypertrophy Classes",
            desc: "<strong>Cost: 10 influence</strong> - How to build muscle. Doubles the effectiveness of strength.",
            cost: 10,
        },
        {
            id: 5,
            isActive: false,
            isPurchased: false,
            name: "Purge Negative Reviews",
            desc: "<strong>Cost: 10 influence</strong> - No bad comments allowed. Doubles influence generation.",
            cost: 10,
        },
        {
            id: 6,
            isActive: false,
            isPurchased: false,
            name: "Setup High Intensity Interval Training Classes",
            desc: "<strong>Cost: 25 influence</strong> - Get that heart rate up! Doubles the effectiveness of agility.",
            cost: 25,
        },
        {
            id: 7,
            isActive: false,
            isPurchased: false,
            name: "Teach High Reps",
            desc: "<strong>Cost: 50 influence</strong> - How to build endurance. Doubles the effectiveness of endurance.",
            cost: 50,
        },
        {
            id: 8,
            isActive: false,
            isPurchased: false,
            name: "Advanced Advertising Techniques",
            desc: "<strong>Cost: 100 influence</strong> - We are one with the economy. Doubles the effectivess of intelligence.",
            cost: 100,
        },
        {
            id: 9,
            isActive: false,
            isPurchased: false,
            name: "Host Classes in Different Buildings",
            desc: "<strong>Cost: 250 influence</strong> - Doubles gym capacity.",
            cost: 250,
        },
        {
            id: 10,
            isActive: false,
            isPurchased: false,
            name: "Economic Fundamentals",
            desc: "<strong>Cost: 1000 influence</strong> - Double intelligence gain from advertising.",
            cost: 1000,
        },
        {
            id: 11,
            isActive: false,
            isPurchased: false,
            name: "More Effective Designers",
            desc: "<strong>Cost: 2500 influence</strong> - Design is not subjective at all. Doubles the effect of ads on campaign growth.",
            cost: 2500,
        },
        {
            id: 12,
            isActive: false,
            isPurchased: false,
            name: "Efficient Coding",
            desc: "<strong>Cost: 5000 influence</strong> - Ads are doubled per bar fill.",
            cost: 5000,
        },
        {
            id: 13,
            isActive: false,
            isPurchased: false,
            name: "Manager Training",
            desc: "<strong>Cost: 10000 influence</strong> - Marketing managers are twice as effective.",
            cost: 10000,
        },
        {
            id: 14,
            isActive: false,
            isPurchased: false,
            name: "Opening a New Gym",
            desc: "<strong>Cost: 25000 influence</strong> - Unlock Open Gym (prestige).",
            cost: 25000,
        },
        {
            id: 15,
            isActive: false,
            isPurchased: false,
            name: "More Coordination",
            desc: "<strong>Cost: 25 influence</strong> - Ad Coordinators are twice as effective.",
            cost: 25,
        },
        {
            id: 16,
            isActive: false,
            isPurchased: false,
            name: "Teach Technique",
            desc: "<strong>Cost: 2.5 influence</strong> - Teach technique. Doubles the stat modifier that applies to gym and advertising (all stats).",
            cost: 2.5,
        },
        {
            id: 17,
            isActive: false,
            isPurchased: false,
            name: "Certifications",
            desc: "<strong>Cost: 500 influence</strong> - Go legit. Doubles members trained per trainer.",
            cost: 500,
        },
        {
            id: 18,
            isActive: false,
            isPurchased: false,
            name: "Better Classes",
            desc: "<strong>Cost: 2500 influence</strong> - Charge more for classes. Doubles the value of classes on money growth.",
            cost: 2500,
        },
        {
            id: 19,
            isActive: false,
            isPurchased: false,
            name: "Teach Bulking",
            desc: "<strong>Cost: 250 influence</strong> - Eat big to get big. Doubles energy recovery.",
            cost: 250,
        },
        {
            id: 20,
            isActive: false,
            isPurchased: false,
            name: "Manager Training",
            desc: "<strong>Cost: 1000 influence</strong> - Marketing managers are twice as effective.",
            cost: 1000,
        },
    ],
    gymUpgrades: [
        {
            id: 0,
            isActive: false,
            isPurchased: false,
            name: "Rearrange Equipment",
            desc: "<strong>Cost: $1</strong> - Basic space management. Double gym capacity",
            cost: 1,
        },
        {
            id: 1,
            isActive: false,
            isPurchased: false,
            name: "Slimmer Equipment",
            desc: "<strong>Cost: $250</strong> - Basic space management. Double gym capacity",
            cost: 250,
        },
        {
            id: 2,
            isActive: false,
            isPurchased: false,
            name: "Remove Walls",
            desc: "<strong>Cost: $1000</strong> - Let's make even better use of the space we have - no more walls! Double gym capacity",
            cost: 1000,
        },
        {
            id: 3,
            isActive: false,
            isPurchased: false,
            name: "Rent More Space",
            desc: "<strong>Cost: $5000</strong> - Should have done this long ago. Double gym capacity",
            cost: 5000,
        },
        {
            id: 4,
            isActive: false,
            isPurchased: false,
            name: "Second Story",
            desc: "<strong>Cost: $25000</strong> - Adding a new level will make the gym much bigger. Double gym capacity",
            cost: 25000,
        },
        {
            id: 5,
            isActive: false,
            isPurchased: false,
            name: "Open Floor Plan",
            desc: "<strong>Cost: $100</strong> - Everyone must see each other at all times. Double gym capacity",
            cost: 100,
        },
        {
            id: 6,
            isActive: false,
            isPurchased: false,
            name: "Cleaning Stations",
            desc: "<strong>Cost: $2.5</strong> - A must have for any filthy gym. Double the effectivness of nutritionists.",
            cost: 2.5,
        },
        {
            id: 7,
            isActive: false,
            isPurchased: false,
            name: "Tours",
            desc: "<strong>Cost: $5</strong> - Give tours around the facility. Doubles the effectiveness of sales reps.",
            cost: 5,
        },
        {
            id: 8,
            isActive: false,
            isPurchased: false,
            name: "Train the Trainer",
            desc: "<strong>Cost: $10</strong> - They must get better!. Doubles the effectiveness of trainers.",
            cost: 10,
        },
        {
            id: 9,
            isActive: false,
            isPurchased: false,
            name: "Cleaner Facilities",
            desc: "<strong>Cost: $25</strong> - You can call me Mr. Clean. Doubles the stat modifier that applies to gym and advertising (all stats).",
            cost: 25,
        },
        {
            id: 10,
            isActive: false,
            isPurchased: false,
            name: "Cross-Pollinating",
            desc: "<strong>Cost: $50</strong> - Trainers will train the advertising folks. Doubles intelligence gain from advertising.",
            cost: 50,
        },
        {
            id: 11,
            isActive: false,
            isPurchased: false,
            name: "Fundamentals",
            desc: "<strong>Cost: $7500</strong> - Teach everyone the basics. Doubles the stat modifier that applies to gym and advertising (all stats).",
            cost: 7500,
        },
        {
            id: 12,
            isActive: false,
            isPurchased: false,
            name: "Socialize Employees",
            desc: "<strong>Cost: $25000</strong> - Make them all talk to each other. Doubles intelligence gain from advertising.",
            cost: 25000,
        },
        {
            id: 13,
            isActive: false,
            isPurchased: false,
            name: "Virtual Tours",
            desc: "<strong>Cost: $100</strong> - Sales reps can provide virtual tours. Doubles the effectiveness of sales reps.",
            cost: 100,
        },
        {
            id: 14,
            isActive: false,
            isPurchased: false,
            name: "Eating Plans",
            desc: "<strong>Cost: $250</strong> - Nutritionists create custom eating plans for client. Doubles the effectiveness of nutritionists.",
            cost: 250,
        },
        {
            id: 15,
            isActive: false,
            isPurchased: false,
            name: "More Classroom Space",
            desc: "<strong>Cost: $500</strong> - Classes can fit more people, so more money. Doubles the effect of each class on money growth.",
            cost: 500,
        },
        {
            id: 16,
            isActive: false,
            isPurchased: false,
            name: "Tiered Classes",
            desc: "<strong>Cost: $1000</strong> - Make members work to get to the next level. Doubles the amount of classes per program coordinator.",
            cost: 1000,
        },
        {
            id: 17,
            isActive: false,
            isPurchased: false,
            name: "Sales Recruiting",
            desc: "<strong>Cost: $2500</strong> - Pay to help recruit more sales reps. Halves the cost of sales reps.",
            cost: 2500,
        },
        {
            id: 18,
            isActive: false,
            isPurchased: false,
            name: "Trainer Recruiting",
            desc: "<strong>Cost: $5000</strong> - Pay to help recruit more trainers. Halves the cost of trainers.",
            cost: 5000,
        },
        {
            id: 19,
            isActive: false,
            isPurchased: false,
            name: "Program Coordinator Recruiting",
            desc: "<strong>Cost: $15000</strong> - Pay to help recruit more program coordinators. Halves the cost of program coordinators.",
            cost: 15000,
        },
        {
            id: 20,
            isActive: false,
            isPurchased: false,
            name: "Nutritionist Recruiting",
            desc: "<strong>Cost: $10000</strong> - Pay to help recruit more nutritionists. Halves the cost of nutritionists.",
            cost: 10000,
        },
        {
            id: 21,
            isActive: false,
            isPurchased: false,
            name: "Post Fliers Around Town",
            desc: "<strong>Cost: $50</strong> - Post some fliers around town. Doubles money growth.",
            cost: 50,
        },
        {
            id: 22,
            isActive: false,
            isPurchased: false,
            name: "Rent Apartments Upstairs in Exchange for Maintenance",
            desc: "<strong>Cost: $10</strong> - Doubles gym capacity.",
            cost: 10,
        },
        {
            id: 23,
            isActive: false,
            isPurchased: false,
            name: "Pay Members to Advertise at Other Gyms",
            desc: "<strong>Cost: $100000</strong> - Sneaky sneaky! Doubles influence generation.",
            cost: 100000,
        },
        {
            id: 24,
            isActive: false,
            isPurchased: false,
            name: "Hiring Tests",
            desc: "<strong>Cost: $10000</strong> - Let's actually vet out some of these people before hiring. Doubles intelligence gain from advertising.",
            cost: 10000,
        },
    ],
    bw: {
        upgrades: [
            {
                id: 0,
                isActive: false,
                isPurchased: false,
                name: "Homemade Pushup Handles",
                desc: "<strong>Cost: $2.5</strong> - Pushup handles should double my protege's pushup speed. That's how physics work.",
                cost: 2.5,
            },
            {
                id: 1,
                isActive: false,
                isPurchased: false,
                name: "Pay Coach to Teach You",
                desc: "<strong>Cost: $25</strong> - My coach wants to show me the correct way to do pushups and rows. Halves the energy expenditure of pushups and rows.",
                cost: 25,
            },
            {
                id: 2,
                isActive: false,
                isPurchased: false,
                name: "Buy Wooden Gymnastic Rings",
                desc: "<strong>Cost: $50</strong> - These nice, wooden made gymnastic rings should let me do rows at double speed.",
                cost: 50,
            },
            {
                id: 3,
                isActive: false,
                isPurchased: false,
                name: "Pay for Pullup Training",
                desc: "<strong>Cost: $250</strong> - My coach keeps wanting more money. Doubles pullup speed.",
                cost: 250,
            },
            {
                id: 4,
                isActive: false,
                isPurchased: false,
                name: "Pay for Dip Training",
                desc: "<strong>Cost: $250</strong> - It's still worth it to double dip. Doubles dip speed.",
                cost: 250,
            },
            {
                id: 5,
                isActive: false,
                isPurchased: false,
                name: "Pay for Pullup Form Training",
                desc: "<strong>Cost: $500</strong> - I need to reduce the leg swing and coach is there for me. Halves the energy expenditure of pullups.",
                cost: 500,
            },
            {
                id: 6,
                isActive: false,
                isPurchased: false,
                name: "Pay for Dip Form Training",
                desc: "<strong>Cost: $500</strong> - My coach has big plans for keeping tighter in dips. Halves the energy expenditure of dips.",
                cost: 500,
            },
            {
                id: 7,
                isActive: false,
                isPurchased: false,
                name: "Pay for Squat Training",
                desc: "<strong>Cost: $1000</strong> - Coach is really putting me to work. Doubles Squat Speed.",
                cost: 1000,
            },
            {
                id: 8,
                isActive: false,
                isPurchased: false,
                name: "Pay Romanian Deadlift Training",
                desc: "<strong>Cost: $1000</strong> - I better be good enough to take over this gym by the end of it. Doubles Romanian Deadlift Speed.",
                cost: 1000,
            },
            {
                id: 9,
                isActive: false,
                isPurchased: false,
                name: "Pay for Leg Hypertrophy Guide",
                desc: "<strong>Cost: $2500</strong> - Seems reasonable, coach is reselling it. Halves the energy expenditure of bodyweight leg exercises.",
                cost: 2500,
            },
            {
                id: 10,
                isActive: false,
                isPurchased: false,
                name: "Better Form for Pushups and Rows",
                desc: "<strong>Cost: $5000</strong> - Best coach I've ever had, hands down. Double energy expenditure of pushups and rows, but double stat gains as well.",
                cost: 5000,
            },
            {
                id: 11,
                isActive: false,
                isPurchased: false,
                name: "Better Form for Dips and Pullups",
                desc: "<strong>Cost: $10000</strong> - Also the only coach I've worked with so far. Double energy expenditure of dips and pullups, but double stat gains as well.",
                cost: 10000,
            },
            {
                id: 12,
                isActive: false,
                isPurchased: false,
                name: "Better Form for Bodyweight Legs Exercises",
                desc: "<strong>Cost: $25000</strong> - I'm nearly ready to take over this gym. Double energy expenditure of bodyweight leg exercises, but double stat gains as well.",
                cost: 25000,
            }
        ],
        gymUpgrades: [

        ],
        adUpgrades: [

        ]
    },
    lifting: {
        upgrades: [
            {
                id: 0,
                isActive: false,
                isPurchased: false,
                name: "Bench Technique",
                desc: "<strong>Cost: $2.5</strong> - Better bench technique will let me rep faster. Doubles bench speed.",
                cost: 2.5,
            },
            {
                id: 1,
                isActive: false,
                isPurchased: false,
                name: "Pay Coach to Teach You",
                desc: "<strong>Cost: $25</strong> - My coach wants to show me the correct way to do bench and rows. Halves the energy expenditure of bench and rows.",
                cost: 25,
            },
            {
                id: 2,
                isActive: false,
                isPurchased: false,
                name: "Grip Training",
                desc: "<strong>Cost: $50</strong> - Get some grip trainers to practice holding onto the bar better. Doubles row speed.",
                cost: 50,
            },
            {
                id: 3,
                isActive: false,
                isPurchased: false,
                name: "Pay for Overhead Press Training",
                desc: "<strong>Cost: $250</strong> - My coach keeps wanting more money. Doubles overhead press speed.",
                cost: 250,
            },
            {
                id: 4,
                isActive: false,
                isPurchased: false,
                name: "Pay for Curl Training",
                desc: "<strong>Cost: $250</strong> - Get those massive biceps. Doubles curl speed.",
                cost: 250,
            },
            {
                id: 5,
                isActive: false,
                isPurchased: false,
                name: "Pay for Overhead Press Form Training",
                desc: "<strong>Cost: $500</strong> - I'm losing the bar in front of me, and coach is there for me. Halves the energy expenditure of overhead press.",
                cost: 500,
            },
            {
                id: 6,
                isActive: false,
                isPurchased: false,
                name: "Pay for Curl Form Training",
                desc: "<strong>Cost: $500</strong> - Curls are very hard to do correctly. Halves the energy expenditure of curls.",
                cost: 500,
            },
            {
                id: 7,
                isActive: false,
                isPurchased: false,
                name: "Pay for Squat Training",
                desc: "<strong>Cost: $1000</strong> - Coach is really putting me to work. Doubles Squat Speed.",
                cost: 1000,
            },
            {
                id: 8,
                isActive: false,
                isPurchased: false,
                name: "Pay Deadlift Training",
                desc: "<strong>Cost: $1000</strong> - I better be good enough to take over this gym by the end of it. Doubles deadlift speed.",
                cost: 1000,
            },
            {
                id: 9,
                isActive: false,
                isPurchased: false,
                name: "Pay for Leg Hypertrophy Guide",
                desc: "<strong>Cost: $2500</strong> - Seems reasonable, coach is reselling it. Halves the energy expenditure of leg exercises.",
                cost: 2500,
            },
            {
                id: 10,
                isActive: false,
                isPurchased: false,
                name: "Better Form for Bench and Rows",
                desc: "<strong>Cost: $5000</strong> - Best coach I've ever had, hands down. Double energy expenditure of bench and rows, but double stat gains as well.",
                cost: 5000,
            },
            {
                id: 11,
                isActive: false,
                isPurchased: false,
                name: "Better Form for Overhead Press and Curls",
                desc: "<strong>Cost: $10000</strong> - Also the only coach I've worked with so far. Double energy expenditure of overhead press and curls, but double stat gains as well.",
                cost: 10000,
            },
            {
                id: 12,
                isActive: false,
                isPurchased: false,
                name: "Better Form for Bodyweight Legs Exercises",
                desc: "<strong>Cost: $25000</strong> - I'm nearly ready to take over this gym. Double energy expenditure of leg exercises, but double stat gains as well.",
                cost: 25000,
            }
        ],
        gymUpgrades: [

        ],
        adUpgrades: [
        ]
    },
    yoga: {
        upgrades: [

        ],
        gymUpgrades: [

        ],
        adUpgrades: [
        ]
    },
    cardio: {
        upgrades: [

        ],
        gymUpgrades: [

        ],
        adUpgrades: [
        ]
    },
}

var prestige = {
    current: 0,
    total: 0,
    upgrades: [
        {
            id: 0,
            isActive: false,
            isPurchased: false,
            name: "Loyal Employees",
            desc: "<strong>Cost: 2 Global Points</strong> - Always start with one of each gym employee and +$10.",
            cost: 2
        },
        {
            id: 1,
            isActive: false,
            isPurchased: false,
            name: "Still Insta-Famous",
            desc: "<strong>Cost: 1 Global Point</strong> - Always start with a flat $.10/s. This money is not affected by any doubling upgrades",
            cost: 1
        },
        {
            id: 2,
            isActive: false,
            isPurchased: false,
            name: "Meditation",
            desc: "<strong>Cost: 3 Global Points</strong> - Double energy recovery and max energy",
            cost: 3
        },
        {
            id: 3,
            isActive: false,
            isPurchased: false,
            name: "More Loyalty",
            desc: "<strong>Cost: 2 Global Points</strong> - Is this deserved? Always start with one of each advertising employee and +$10.",
            cost: 2
        },
        {
            id: 4,
            isActive: false,
            isPurchased: false,
            name: "Bigger Starting Locations",
            desc: "<strong>Cost: 3 Global Points</strong> - Doubles starting gym capacity.",
            cost: 3
        },
        {
            id: 5,
            isActive: false,
            isPurchased: false,
            name: "Faster Training",
            desc: "<strong>Cost: 4 Global Points</strong> - Doubles trainer effectiveness.",
            cost: 4
        },
        {
            id: 6,
            isActive: false,
            isPurchased: false,
            name: "Faster Start",
            desc: "<strong>Cost: 4 Global Points</strong> - Strength, endurance, agility, and intelligence all have 10 added at the start.",
            cost: 4
        },
        {
            id: 7,
            isActive: false,
            isPurchased: false,
            name: "Autobuy Sales Reps",
            desc: "<strong>Cost: 5 Global Points</strong> - Buy sales reps as they become available (toggle in options tab).",
            cost: 5
        },
        {
            id: 8,
            isActive: false,
            isPurchased: false,
            name: "Autobuy Trainers",
            desc: "<strong>Cost: 6 Global Points</strong> - Buy trainers as they become available (toggle in options tab).",
            cost: 6
        },
        {
            id: 9,
            isActive: false,
            isPurchased: false,
            name: "Autobuy Ad Coordinators",
            desc: "<strong>Cost: 6 Global Points</strong> - Buy ad coordinators as they become available (toggle in options tab).",
            cost: 6
        },
        {
            id: 10,
            isActive: false,
            isPurchased: false,
            name: "Autobuy Program Coordinators",
            desc: "<strong>Cost: 8 Global Points</strong> - Buy program coordinators as they become available (toggle in options tab).",
            cost: 8
        },
        {
            id: 11,
            isActive: false,
            isPurchased: false,
            name: "Autobuy Ad Designers",
            desc: "<strong>Cost: 8 Global Points</strong> - Buy ad designers as they become available (toggle in options tab).",
            cost: 8
        },
        {
            id: 12,
            isActive: false,
            isPurchased: false,
            name: "Autobuy Nutritionists",
            desc: "<strong>Cost: 10 Global Points</strong> - Buy nutritionists as they become available (toggle in options tab).",
            cost: 10
        },
        {
            id: 13,
            isActive: false,
            isPurchased: false,
            name: "Autobuy Marketing Managers",
            desc: "<strong>Cost: 10 Global Points</strong> - Buy marketing managers as they become available (toggle in options tab).",
            cost: 10
        },
        {
            id: 14,
            isActive: false,
            isPurchased: false,
            name: "Powerful",
            desc: "<strong>Cost: 20 Global Points</strong> - Doubles strength modifier.",
            cost: 20
        },
        {
            id: 15,
            isActive: false,
            isPurchased: false,
            name: "Long-Lasting",
            desc: "<strong>Cost: 20 Global Points</strong> - Doubles endurance modifier.",
            cost: 20
        },
        {
            id: 16,
            isActive: false,
            isPurchased: false,
            name: "Speedy",
            desc: "<strong>Cost: 20 Global Points</strong> - Doubles agility modifier.",
            cost: 20
        },
        {
            id: 17,
            isActive: false,
            isPurchased: false,
            name: "Braniac",
            desc: "<strong>Cost: 20 Global Points</strong> - Doubles intelligence modifier.",
            cost: 20
        },
        {
            id: 18,
            isActive: false,
            isPurchased: false,
            name: "Good Business",
            desc: "<strong>Cost: 20 Global Points</strong> - Doubles gym and advertising modifier (all stats).",
            cost: 20
        },
        {
            id: 19,
            isActive: false,
            isPurchased: false,
            name: "Good Investing",
            desc: "<strong>Cost: 5 Global Points</strong> - Always start with an additional flat $.10/s. This money is not affected by any doubling upgrades.",
            cost: 5
        },
        {
            id: 20,
            isActive: false,
            isPurchased: false,
            name: "Even More Loyalty",
            desc: "<strong>Cost: 8 Global Points</strong> - Always start with +1 of each gym employee and +$50",
            cost: 8
        },
        {
            id: 21,
            isActive: false,
            isPurchased: false,
            name: "Most Loyalty",
            desc: "<strong>Cost: 8 Global Points</strong> - Always start with +1 of each advertising employee and +$50",
            cost: 8
        },
        {
            id: 22,
            isActive: false,
            isPurchased: false,
            name: "Fastest Start",
            desc: "<strong>Cost: 10 Global Points</strong> - Strength, endurance, agility, and intelligence all have 100 added at the start",
            cost: 10
        },
        {
            id: 23,
            isActive: false,
            isPurchased: false,
            name: "Smarter Advertising",
            desc: "<strong>Cost: 4 Global Points</strong> - Doubles the intelligence generation of advertising.",
            cost: 4
        },
        {
            id: 24,
            isActive: false,
            isPurchased: false,
            name: "Intravenous Coffee",
            desc: "<strong>Cost: 15 Global Points</strong> - Autoclicks coffee (toggle in options tab).",
            cost: 15
        },
        {
            id: 25,
            isActive: false,
            isPurchased: false,
            name: "Focused Training",
            desc: "<strong>Cost: 5 Global Points</strong> - Choose which tier to focus on for trainers.",
            cost: 5
        },
        {
            id: 26,
            isActive: false,
            isPurchased: false,
            name: "Lifting Gyms",
            desc: "<strong>Cost: 5 Global Points</strong> - Unlock lifting gyms.",
            cost: 5
        },
    ],
    bw: {
        current: 0,
        total: 0,
        confidence: 0,
        confidenceBoost: 0,
        upgrades: [
            {
                id: 0,
                isActive: false,
                isPurchased: false,
                name: "Street Workout Gangs",
                desc: "<strong>Cost: 1 Bodyweight Point</strong> - Unlock street workout gangs.",
                cost: 1
            },
            {
                id: 1,
                isActive: false,
                isPurchased: false,
                name: "Unlock Permanent Confidence",
                desc: "<strong>Cost: 2 Bodyweight Points</strong> - Confidence gained from absorbing gangs provides a permanent 2% per point boost to all gym functions.",
                cost: 2
            },
            {
                id: 2,
                isActive: false,
                isPurchased: false,
                name: "Half-Energy Pushups",
                desc: "<strong>Cost: 2 Bodyweight Points</strong> - Pushups use half the energy.",
                cost: 2
            },
            {
                id: 3,
                isActive: false,
                isPurchased: false,
                name: "Half-Energy Rows",
                desc: "<strong>Cost: 2 Bodyweight Points</strong> - Rows use half the energy.",
                cost: 2
            },
            {
                id: 4,
                isActive: false,
                isPurchased: false,
                name: "Half-Energy Dips",
                desc: "<strong>Cost: 3 Bodyweight Points</strong> - Dips use half the energy.",
                cost: 3
            },
            {
                id: 5,
                isActive: false,
                isPurchased: false,
                name: "Half-Energy Pullups",
                desc: "<strong>Cost: 3 Bodyweight Points</strong> - Pullups use half the energy.",
                cost: 3
            },
            {
                id: 6,
                isActive: false,
                isPurchased: false,
                name: "Double Stat Pushups",
                desc: "<strong>Cost: 4 Bodyweight Points</strong> - Pushups give double stats per bar fill.",
                cost: 4
            },
            {
                id: 7,
                isActive: false,
                isPurchased: false,
                name: "Double Stat Rows",
                desc: "<strong>Cost: 4 Bodyweight Points</strong> - Rows give double stats per bar fill.",
                cost: 4
            },
            {
                id: 8,
                isActive: false,
                isPurchased: false,
                name: "Half-Energy Squats",
                desc: "<strong>Cost: 5 Bodyweight Points</strong> - Squats use half the energy.",
                cost: 5
            },
            {
                id: 9,
                isActive: false,
                isPurchased: false,
                name: "Half-Energy Romanian Deadlifts",
                desc: "<strong>Cost: 5 Bodyweight Points</strong> - Romanian Deadlifts use half the energy.",
                cost: 5
            },
            {
                id: 10,
                isActive: false,
                isPurchased: false,
                name: "Double Stat Dips",
                desc: "<strong>Cost: 6 Bodyweight Points</strong> - Dips give double stats per bar fill.",
                cost: 6
            },
            {
                id: 11,
                isActive: false,
                isPurchased: false,
                name: "Double Stat Pullups",
                desc: "<strong>Cost: 6 Bodyweight Points</strong> - Pullups give double stats per bar fill.",
                cost: 6
            },
            {
                id: 12,
                isActive: false,
                isPurchased: false,
                name: "Double Stat Squats",
                desc: "<strong>Cost: 8 Bodyweight Points</strong> - Squats give double stats per bar fill.",
                cost: 8
            },
            {
                id: 13,
                isActive: false,
                isPurchased: false,
                name: "Double Stat Romanian Deadlifts",
                desc: "<strong>Cost: 8 Bodyweight Points</strong> - Romanian Deadlifts give double stats per bar fill.",
                cost: 8
            },
            {
                id: 14,
                isActive: false,
                isPurchased: false,
                name: "Autobuy Workout Upgrades",
                desc: "<strong>Cost: 10 Bodyweight Points</strong> - Buy workout upgrades as they become available (toggle in options tab).",
                cost: 10
            },
            {
                id: 15,
                isActive: false,
                isPurchased: false,
                name: "Autobuy Gym Upgrades",
                desc: "<strong>Cost: 10 Bodyweight Points</strong> - Buy gym upgrades as they become available (toggle in options tab).",
                cost: 10
            },
            {
                id: 16,
                isActive: false,
                isPurchased: false,
                name: "Autobuy Advertising Upgrades",
                desc: "<strong>Cost: 10 Bodyweight Points</strong> - Buy advertising upgrades as they become available (toggle in options tab).",
                cost: 10
            },
            {
                id: 17,
                isActive: false,
                isPurchased: false,
                name: "Gang Recruiting",
                desc: "<strong>Cost: 2 Bodyweight Points</strong> - Double member recruitment for the gang.",
                cost: 2
            },
            {
                id: 18,
                isActive: false,
                isPurchased: false,
                name: "Gang Workouts",
                desc: "<strong>Cost: 2 Bodyweight Points</strong> - Double strength gain for the gang.",
                cost: 2
            },
            {
                id: 19,
                isActive: false,
                isPurchased: false,
                name: "Gang Colors",
                desc: "<strong>Cost: 15 Bodyweight Points</strong> - Auto-Absorb Gangs (toggle in options tab).",
                cost: 15
            },
        ]
    },
    lifting: {
        current: 0,
        total: 0,
        leadership: 0,
        leadershipBoost: 0,
        upgrades: [
            {
                id: 0,
                isActive: false,
                isPurchased: false,
                name: "Competitions",
                desc: "<strong>Cost: 1 Lifting Point</strong> - Unlock competitions.",
                cost: 1
            },
            {
                id: 1,
                isActive: false,
                isPurchased: false,
                name: "Unlock Permanent Leadership",
                desc: "<strong>Cost: 2 Lifting Points</strong> - Leadership gained from creating world-wide conferences provides a permanent 2% per point boost to all stat gain.",
                cost: 2
            },
            {
                id: 2,
                isActive: false,
                isPurchased: false,
                name: "Half-Energy Bench",
                desc: "<strong>Cost: 2 Lifting Points</strong> - Bench uses half the energy.",
                cost: 2
            },
            {
                id: 3,
                isActive: false,
                isPurchased: false,
                name: "Half-Energy Rows",
                desc: "<strong>Cost: 2 Lifting Points</strong> - Rows use half the energy.",
                cost: 2
            },
            {
                id: 4,
                isActive: false,
                isPurchased: false,
                name: "Half-Energy Overhead Press",
                desc: "<strong>Cost: 3 Lifting Points</strong> - Overhead press uses half the energy.",
                cost: 3
            },
            {
                id: 5,
                isActive: false,
                isPurchased: false,
                name: "Half-Energy Curls",
                desc: "<strong>Cost: 3 Lifting Points</strong> - Curls use half the energy.",
                cost: 3
            },
            {
                id: 6,
                isActive: false,
                isPurchased: false,
                name: "Double Stat Bench",
                desc: "<strong>Cost: 4 Lifting Points</strong> - Bench gives double stats per bar fill.",
                cost: 4
            },
            {
                id: 7,
                isActive: false,
                isPurchased: false,
                name: "Double Stat Rows",
                desc: "<strong>Cost: 4 Lifting Points</strong> - Rows give double stats per bar fill.",
                cost: 4
            },
            {
                id: 8,
                isActive: false,
                isPurchased: false,
                name: "Half-Energy Squats",
                desc: "<strong>Cost: 5 Lifting Points</strong> - Squats use half the energy.",
                cost: 5
            },
            {
                id: 9,
                isActive: false,
                isPurchased: false,
                name: "Half-Energy Deadlifts",
                desc: "<strong>Cost: 5 Lifting Points</strong> - Deadlifts use half the energy.",
                cost: 5
            },
            {
                id: 10,
                isActive: false,
                isPurchased: false,
                name: "Double Stat Overhead press",
                desc: "<strong>Cost: 6 Lifting Points</strong> - Overhead press gives double stats per bar fill.",
                cost: 6
            },
            {
                id: 11,
                isActive: false,
                isPurchased: false,
                name: "Double Stat Curls",
                desc: "<strong>Cost: 6 Lifting Points</strong> - Curls give double stats per bar fill.",
                cost: 6
            },
            {
                id: 12,
                isActive: false,
                isPurchased: false,
                name: "Double Stat Squats",
                desc: "<strong>Cost: 8 Lifting Points</strong> - Squats give double stats per bar fill.",
                cost: 8
            },
            {
                id: 13,
                isActive: false,
                isPurchased: false,
                name: "Double Stat Deadlifts",
                desc: "<strong>Cost: 8 Lifting Points</strong> - Deadlifts give double stats per bar fill.",
                cost: 8
            },
            {
                id: 14,
                isActive: false,
                isPurchased: false,
                name: "Autobuy Workout Upgrades",
                desc: "<strong>Cost: 10 Lifting Points</strong> - Buy workout upgrades as they become available (toggle in options tab).",
                cost: 10
            },
            {
                id: 15,
                isActive: false,
                isPurchased: false,
                name: "Autobuy Gym Upgrades",
                desc: "<strong>Cost: 10 Lifting Points</strong> - Buy gym upgrades as they become available (toggle in options tab).",
                cost: 10
            },
            {
                id: 16,
                isActive: false,
                isPurchased: false,
                name: "Autobuy Advertising Upgrades",
                desc: "<strong>Cost: 10 Lifting Points</strong> - Buy advertising upgrades as they become available (toggle in options tab).",
                cost: 10
            },
            {
                id: 17,
                isActive: false,
                isPurchased: false,
                name: "Competition Strength",
                desc: "<strong>Cost: 4 Lifting Points</strong> - Lifting weights provide double the modifier for competitions.",
                cost: 4
            },
            {
                id: 18,
                isActive: false,
                isPurchased: false,
                name: "Conference Help",
                desc: "<strong>Cost: 15 Lifting Points</strong> - Autobuy Conferences (toggle in options tab).",
                cost: 15
            },
        ],
    },
    yoga: {
        current: 0,
        total: 0,
        upgrades: [

        ],
    },
    cardio: {
        current: 0,
        total: 0,
        upgrades: [

        ],
    }
};

var checks = {
    isResting: false,
    isPrestige: false,
    gymType: -1,
    story1: false,
    story2: false,
    story3: false,
    story4: false,
    story5: false,
    story6: false,
    gymSalesBuyer: false,
    gymSalesBuyerOn: false,
    gymTrainerBuyer: false,
    gymTrainerBuyerOn: false,
    gymCoordinatorBuyer: false,
    gymCoordinatorBuyerOn: false,
    gymNutritionistBuyer: false,
    gymNutritionistBuyerOn: false,
    adCoordinatorBuyer: false,
    adCoordinatorBuyerOn: false,
    adDesignerBuyer: false,
    adDesignerBuyerOn: false,
    adManagerBuyer: false,
    adManagerBuyerOn: false,
    bwUpgradeBuyer: false,
    bwUpgradeBuyerOn: false,
    bwGymBuyer: false,
    bwGymBuyerOn: false,
    bwAdBuyer: false,
    bwAdBuyerOn: false,
    liftingUpgradeBuyer: false,
    liftingUpgradeBuyerOn: false,
    liftingGymBuyer: false,
    liftingGymBuyerOn: false,
    liftingAdBuyer: false,
    liftingAdBuyerOn: false,
    coffeeClicker: false,
    coffeeClickerOn: false,
    absorbGangs: false,
    absorbGangsOn: false,
    conferenceBuyer: false,
    conferenceBuyerOn: false,
};


var baseStats = JSON.parse(JSON.stringify(stats));
var baseBodyweight = JSON.parse(JSON.stringify(bodyweight));
var baseUpgrades = JSON.parse(JSON.stringify(upgrades));
var baseJob = JSON.parse(JSON.stringify(job));
var baseResearch = JSON.parse(JSON.stringify(research));
var baseChecks = JSON.parse(JSON.stringify(checks));
var baseGym = JSON.parse(JSON.stringify(gym));
var basePrestige = JSON.parse(JSON.stringify(prestige));
var baseLifting = JSON.parse(JSON.stringify(lifting));